IF
 !Allegiance(Myself,ENEMY) !Global("MAP_GROUP_HOSTILE1","MYAREA",0)
THEN
 RESPONSE #100 Enemy() SetGlobal("MAP_GROUP_HOSTILE1","MYAREA",1) Continue()
END
IF
 Global("GOING_TO_TEMPLE","LOCALS",0) !NumTimesTalkedTo(0)
THEN
 RESPONSE #100 SetGlobal("GOING_TO_TEMPLE","LOCALS",1) Continue()
END
IF
 Global("MAP_GROUP_HOSTILE1","MYAREA",0) See(NearestEnemyOf(Myself))
THEN
 RESPONSE #100 SetGlobal("MAP_GROUP_HOSTILE1","MYAREA",1) Continue()
END
