IF
 Global("MOVE_DEST","LOCALS",0)
THEN
 RESPONSE #100 SetGlobal("MOVE_DEST","LOCALS",1) SetGlobalTimer("#localtimer","LOCALS",7) RESPONSE #100 SetGlobal("MOVE_DEST","LOCALS",2) SetGlobalTimer("#localtimer","LOCALS",7) RESPONSE #100 SetGlobal("MOVE_DEST","LOCALS",3) SetGlobalTimer("#localtimer","LOCALS",7) RESPONSE #100 SetGlobal("MOVE_DEST","LOCALS",4) SetGlobalTimer("#localtimer","LOCALS",7) RESPONSE #100 SetGlobal("MOVE_DEST","LOCALS",5) SetGlobalTimer("#localtimer","LOCALS",7)
END
