IF TRIGGER
   TriggerBlock(HLAMage|CoreMinusPrep)
        IgnoreBlock(IsBG1Only)
THEN DO
     Action(SpellL7Myself,WIZARD_ENERGY_BLADES|100|100)
END

IF TRIGGER
        IgnoreBlock(IsBG1Only)
   RequireBlock(IsIWDArcane)
   RequireBlock(SCSIWDArcane)
   !HasItem("msword",Myself)
   !Global("instantprep","LOCALS",0)  // don't accidentally cast two of them
THEN DO
   Action(SpellMyself,WIZARD_MORDENKAINENS_SWORD_IWD|100|100)
END