IF TRIGGER
	TargetBlock(PCFighters)
	TriggerBlock(Enemy|Helpless|MR|MinorGlobe|SpellTurn)
	CheckStatGT(scstarget,9,STR)
	CheckStatGT(scstarget,0,SAVEVSSPELL)
THEN DO
	Combine()
	Action(Spell,WIZARD_RAY_OF_ENFEEBLEMENT|150|50)
END

IF TRIGGER
	TargetBlock(PCFighters)
	TriggerBlock(Enemy|Helpless|MR|MinorGlobe|SpellTurn)
	CheckStatGT(scstarget,0,SAVEVSSPELL)
	!StateCheck(scstarget,STATE_BLIND)
THEN DO
	Combine()
	Action(Spell,WIZARD_BLINDNESS|150|50)
END
