//////////////////////////////////////////////////////////////////////////
///	Core combat script
///	NB - must be embedded in something that fills in slowspell    /////
//////////////////////////////////////////////////////////////////////////





INCLUDE FILE (%scsroot%/mage/ssl/bg2/combatblocks/kill_summons_if_no_PC.ssl)
INCLUDE FILE (%scsroot%/mage/ssl/bg2/combatblocks/renew_antimagic.ssl)
INCLUDE FILE (%scsroot%/mage/ssl/bg2/combatblocks/attacks_on_PC_defences.ssl)
INCLUDE FILE (%scsroot%/mage/ssl/bg2/combatblocks/truesight.ssl)
INCLUDE FILE (%scsroot%/mage/ssl/bg2/combatblocks/hla.ssl)
INCLUDE FILE (%scsroot%/mage/ssl/bg2/combatblocks/high_level_fire_magic.ssl)
INCLUDE FILE (%scsroot%/mage/ssl/bg2/combatblocks/highpowered_area_attacks.ssl)
INCLUDE FILE (%scsroot%/demilich/ssl/trap_the_soul.ssl)
INCLUDE FILE (%scsroot%/mage/ssl/bg2/combatblocks/power_word_blind.ssl)
INCLUDE FILE (%scsroot%/mage/ssl/bg2/combatblocks/areadenial.ssl)
INCLUDE FILE (%scsroot%/mage/ssl/bg2/combatblocks/attack_antimagic.ssl)
INCLUDE FILE (%scsroot%/mage/ssl/bg2/combatblocks/kill_summons.ssl)
INCLUDE FILE (%scsroot%/mage/ssl/bg2/combatblocks/kill-maze-stun.ssl)
INCLUDE FILE (%scsroot%/mage/ssl/bg2/combatblocks/mid_level_area.ssl)
INCLUDE FILE (%scsroot%/mage/ssl/bg2/combatblocks/low_level_area.ssl)
INCLUDE FILE (%scsroot%/mage/ssl/bg2/combatblocks/flame_arrows.ssl)
INCLUDE FILE (%scsroot%/mage/ssl/bg2/combatblocks/arrows.ssl)
INCLUDE FILE (%scsroot%/mage/ssl/bg2/combatblocks/low_level_disabling.ssl)
INCLUDE FILE (%scsroot%/mage/ssl/bg2/combatblocks/renew_melf.ssl)




