IF
	!Global("bareshprep","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("bareshprep","LOCALS",1)
		CreateItem("potn52",0,0,0)
		CreateItem("%tutu_var%POTN05",0,0,0)
		CreateItem("potn52",0,0,0)
		CreateItem("%tutu_var%POTN35",0,0,0)
		CreateItem("dw#noptn",0,0,0)
END

IF
	OR(2)
		HPPercentLT(Myself,10)
		Dead("mendas3")
	Global("transformed","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("transformed","LOCALS",1)
		DestroyItem("minhp1")
		ApplySpellRES("dw#barwf",Myself)
END

