DEFAULT TRIGGER(OR(2) HasItem("harm",Myself) HasItem("dw#harmn",Myself))

IF TRIGGER
          RequireBlock(HasL6)
	Target(WorstAC())
	TargetBlock(PCsInOrder)
	TargetBlock(EnemiesInOrderShort)
	Range(scstarget,10)
	TriggerBlock(SpellTurn|SINecromancy|MirrorImage|MRTouch)
	!CheckStat(scstarget,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
THEN DO
	Action(Attack)
END

DEFAULT TRIGGER(HasItem("slaylive",Myself))

IF TRIGGER
          RequireBlock(HasL5)
	Target(WorstAC())
	TargetBlock(PCsInOrder)
	TargetBlock(EnemiesInOrderShort)
	Range(scstarget,10)
	TriggerBlock(SpellTurn|SINecromancy|MRTouch|MirrorImage|Slay)
	!CheckStat(scstarget,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
THEN DO
	Action(Attack)
END

DEFAULT TRIGGER()

