
ACTION_IF !GAME_IS "eet bgee bg2ee iwdee" BEGIN  // enforce enhanced-edition
   FAIL "Requires enhanced edition"
END

////////////////////////////////////////////////////////
////////////////////////////////////////////////////////
//// 	Things to do only once
////////////////////////////////////////////////////////
////////////////////////////////////////////////////////

ACTION_IF !VARIABLE_IS_SET ~initialise~ BEGIN
    OUTER_SET initialise=1

////////////////////////////////////////////////////////
//// general variables, macros and functions
////////////////////////////////////////////////////////
  ACTION_IF !VARIABLE_IS_SET do_not_biff BEGIN
     OUTER_SET do_not_biff=0
  END

  ACTION_IF !VARIABLE_IS_SET sfo_loc BEGIN
      OUTER_SPRINT sfo_loc "sfo"
  END
  ACTION_IF !VARIABLE_IS_SET sfo_loc BEGIN
      OUTER_SPRINT ssl_loc "ssl"
  END
  INCLUDE ~%MOD_FOLDER%/%sfo_loc%/install_sfo.tpa~

  OUTER_SPRINT ssllibrary "%MOD_FOLDER%/%ssl_loc%/library.slb"

////////////////////////////////////////////////////////
//// On BG2EE, include DS
////////////////////////////////////////////////////////

  ACTION_IF GAME_IS "bgee bg2ee eet" BEGIN
     LAF include STR_VAR file="ds.tph" location="%iwdspells_lib%" END
  END

END
