DEFINE_ACTION_FUNCTION elemental_summoning_sr BEGIN

	LAF check_label STR_VAR label=dw_iwd_sr_elementals RET value END
	ACTION_IF !value BEGIN
		LAF make_label STR_VAR label=dw_iwd_sr_elementals END
		
		/////////////////////////////
		// get some data
		//////////////////////////////
		
		COPY_EXISTING_REGEXP - "es8watr.cre" nowhere
			READ_BYTE 0x273 water_elem_class
			READ_LONG 0x28 water_elem_anim
			SET $water_elem_names("STANDARD")=LONG_AT NAME1

		COPY_EXISTING - "%WIZARD_CONJURE_LESSER_WATER_ELEMENTAL%.spl" nowhere
			conjure_water_strref=LONG_AT NAME1

		OUTER_SET $water_elem_names("GREATER")=73479
		OUTER_SET $water_elem_names("ELDER")= RESOLVE_STR_REF (@8)
		OUTER_SET $water_elem_names("LESSER")= RESOLVE_STR_REF (@9)
		
		///////////////////////////////////////////////////////////////////////
		// adjust the L5 Conjure Lesser Water Elemental to match SR conventions
		////////////////////////////////////////////////////////////////////////

		// the icons	
		ACTION_FOR_EACH letter IN A B C BEGIN
			COPY_EXISTING "%WIZARD_CONJURE_LESSER_WATER_ELEMENTAL%%letter%.bam" "%workspace%/water_icon%letter%.bam"
		END
		
		// spell
		COPY_EXISTING "%WIZARD_CONJURE_LESSER_EARTH_ELEMENTAL%.spl" "override/%WIZARD_CONJURE_LESSER_WATER_ELEMENTAL%.spl"
			SAY NAME1 @7
			SAY 0x50 @300
			REPLACE_TEXTUALLY "%WIZARD_CONJURE_LESSER_EARTH_ELEMENTAL%" "%WIZARD_CONJURE_LESSER_WATER_ELEMENTAL%"
			LPF ALTER_EFFECT STR_VAR match_resource=SPLESEAR resource=DWLESWAT END
		
		// scroll	

		COPY_EXISTING "%WIZARD_CONJURE_LESSER_WATER_ELEMENTAL_SCROLL%.itm" override
			SAY NAME2 @7
			SAY 0x54 @300
			
		// summoning effect
		COPY_EXISTING "SPLESEAR.eff" "override/DWLESWAT.eff"
			WRITE_ASCII 0x30 es8watr (8)
	
		// cre file
		
		COPY_EXISTING "elearsu.cre" "override/es8watr.cre"
			WRITE_BYTE 0x273 water_elem_class
			WRITE_LONG 0x28 water_elem_anim
			WRITE_LONG 0x8 water_elem_names_LESSER
			WRITE_LONG 0xc water_elem_names_LESSER
			WRITE_SHORT 0x24 80 // hp
			WRITE_SHORT 0x26 80
			WRITE_SHORT 0x46 2  // AC
			WRITE_SHORT 0x48 2
			WRITE_SHORT 0x59 50 // fire resistance
			WRITE_SHORT 0x5e 50
			WRITE_SHORT 0x5a 50 // cold resistance
			WRITE_SHORT 0x5f 50
			WRITE_SHORT 0x60 30 // physical resistance
			WRITE_SHORT 0x61 30 
			WRITE_SHORT 0x62 30 
			WRITE_SHORT 0x63 30 
			WRITE_BYTE 0x238 18 // strength
			WRITE_BYTE 0x239 76 // ex.strength
			WRITE_BYTE 0x23c 17 // dex
			WRITE_BYTE 0x23d 16 // con
			ADD_CRE_ITEM dwelwat1 #0 #0 #0 NONE WEAPON1 EQUIP
			REMOVE_CRE_ITEM elearsu1
				
		// weapon
			
		COPY_EXISTING "elearsu1.itm" "override/dwelwat1.itm"
			LPF DELETE_EFFECT INT_VAR match_opcode=126 END
		
		///////////////////////////////////////////////////////////////////////
		// create a L6 Conjure Water Elemental to match SR conventions
		////////////////////////////////////////////////////////////////////////

		// spell, scroll
		
		WIZARD_CONJURE_WATER_ELEMENTAL,WIZARD_CONJURE_WATER_ELEMENTAL_SCROLL=spl.copy["%WIZARD_CONJURE_EARTH_ELEMENTAL%"=>WIZARD_CONJURE_WATER_ELEMENTAL|icon_base_name=water_icon icon_path="%workspace%"]
		[
			m_name-strref=conjure_water_strref
			m_description:=@301
			m.ab_fx.alter{PATCH_IF !"%s_resource%" STRING_CONTAINS_REGEXP "SPEART1" BEGIN SPRINT s_resource dw#wat1 END ELSE BEGIN SPRINT s_resource dw#wat2 END|match="s_opcode=177"}
		]
		
		// effects
		
		COPY_EXISTING "speart1.eff" "override/dw#wat1.eff"
			WRITE_ASCII 0x30 "DW#WATE2"
		
		COPY_EXISTING "speart2.eff" "override/dw#wat2.eff"
			WRITE_ASCII 0x30 "DW#WATE3"

		// cre files
		
		COPY_EXISTING "ELEARSU2.CRE" "override/dw#wate2.cre"
			WRITE_LONG 0x8 water_elem_names_STANDARD
			WRITE_LONG 0xc water_elem_names_STANDARD
			WRITE_BYTE 0x273 water_elem_class
			WRITE_LONG 0x28 water_elem_anim
			WRITE_SHORT 0x24 126 // hp
			WRITE_SHORT 0x26 126
			WRITE_SHORT 0x46 1 // AC
			WRITE_SHORT 0x48 1
			WRITE_SHORT 0x59 50 // fire resistance
			WRITE_SHORT 0x5e 50
			WRITE_SHORT 0x5a 50 // cold resistance
			WRITE_SHORT 0x5f 50
			WRITE_SHORT 0x60 30 // physical resistance
			WRITE_SHORT 0x61 30 
			WRITE_SHORT 0x62 30 
			WRITE_SHORT 0x63 30 
			WRITE_BYTE 0x238 19 // strength
			WRITE_BYTE 0x23c 18 // dex
			WRITE_BYTE 0x23d 17 // con
			ADD_CRE_ITEM dwelwat2 #0 #0 #0 NONE WEAPON1 EQUIP
			REMOVE_CRE_ITEM elearsu2

		COPY_EXISTING "ELEARSU3.CRE" "override/dw#wate3.cre"
			WRITE_LONG 0x8 water_elem_names_GREATER
			WRITE_LONG 0xc water_elem_names_GREATER
			WRITE_BYTE 0x273 water_elem_class
			WRITE_LONG 0x28 water_elem_anim
			WRITE_SHORT 0x24 152 // hp
			WRITE_SHORT 0x26 152
			WRITE_SHORT 0x46 0 // AC
			WRITE_SHORT 0x48 0
			WRITE_SHORT 0x59 50 // fire resistance
			WRITE_SHORT 0x5e 50
			WRITE_SHORT 0x5a 50 // cold resistance
			WRITE_SHORT 0x5f 50
			WRITE_SHORT 0x60 30 // physical resistance
			WRITE_SHORT 0x61 30 
			WRITE_SHORT 0x62 30 
			WRITE_SHORT 0x63 30 
			WRITE_BYTE 0x238 21 // strength
			WRITE_BYTE 0x23c 19 // dex
			WRITE_BYTE 0x23d 18 // con
			ADD_CRE_ITEM dwelwat3 #0 #0 #0 NONE WEAPON1 EQUIP
			REMOVE_CRE_ITEM elearsu3

		// weapons
			
		COPY_EXISTING 
			"elearsu2.itm" "override/dwelwat2.itm"
			"elearsu3.itm" "override/dwelwat3.itm"
				LPF DELETE_EFFECT INT_VAR match_opcode=126 END

		// scroll placement
		
		OUTER_SPRINT scroll_old "%WIZARD_CONJURE_AIR_ELEMENTAL_SCROLL%" // only bother if it exists
		ACTION_IF FILE_EXISTS_IN_GAME "%scroll_old%.itm" BEGIN
			COPY_EXISTING_REGEXP GLOB ".*\.sto" override
				PATCH_IF INDEX_BUFFER ("%scroll_old%")>=0 BEGIN
					LPF struct_read RET_ARRAY m=struct END
					LPF struct_clone 
						STR_VAR 
							type=item 
							struct=m 
							match="~%s_resref%~==%scroll_old%" 
							patch="s_resref:=~%WIZARD_CONJURE_WATER_ELEMENTAL_SCROLL%~"
						RET_ARRAY m=struct END
					LPF struct_write STR_VAR struct=m END
				END
			BUT_ONLY
		END

		///////////////////////////////////////////////////////////////
		// install Cam's replacement icons for the Lesser series
		///////////////////////////////////////////////////////////////

		ACTION_BASH_FOR "%MOD_FOLDER%/%component_loc%/resource/elem_icons" "SPWI.*\.bam" BEGIN
			COPY "%BASH_FOR_FILESPEC%" override
		END
		ACTION_FOR_EACH letter IN A B C BEGIN
			COPY "%MOD_FOLDER%/%component_loc%/resource/elem_icons/clwater%letter%.bam" "override/%WIZARD_CONJURE_LESSER_WATER_ELEMENTAL%%letter%.bam"
		END


	END
END
