DEFINE_ACTION_FUNCTION force_blade BEGIN

   ACTION_IF VARIABLE_IS_SET $IWD_spell_installed("WIZARD_MORDENKAINENS_SWORD_IWD") || is_iwd BEGIN

		// rename the spell [this is only a partial edit-in-place, because 'Mordenkainen's Sword' is used in both spells!
		spl.edit["%WIZARD_MORDENKAINENS_SWORD_IWD%"]
		[
			new_name:=@10
			strref.patch{m_description-strref}{REPLACE_TEXTUALLY "%m_name%" "%new_name%"}
			m_name:="%new_name%"
		]
		// rename the scroll (description is auto-updated)
		itm.edit["%WIZARD_MORDENKAINENS_SWORD_IWD_SCROLL%"]
		[
			m_identified_name:=@10
		]
		
		// Reverse the icons, since the green one (attached to SWORD_IWD) ought to be associated with the summons effect

		ACTION_FOR_EACH letter IN a b c BEGIN
			 COPY_EXISTING "%WIZARD_MORDENKAINENS_SWORD_IWD%%letter%.bam" "%workspace%"
			 COPY_EXISTING "%WIZARD_MORDENKAINENS_SWORD%%letter%.bam" "override/%WIZARD_MORDENKAINENS_SWORD_IWD%%letter%.bam"
			 COPY "%workspace%/%WIZARD_MORDENKAINENS_SWORD_IWD%%letter%.bam" "override/%WIZARD_MORDENKAINENS_SWORD%%letter%.bam"
		END
		
		ACTION_IF is_iwd BEGIN
			// on IWD, manually make a scroll and add it to the store
			LAF spl_make_scroll
				STR_VAR spell_resref="%WIZARD_MORDENKAINENS_SWORD%"
				RET scroll_resref
			END	
			COPY_EXISTING edion.sto override
				ADD_STORE_ITEM "%scroll_resref%" AFTER SCRL8F #1 #0 #0  IDENTIFIED #1
			BUT_ONLY
		END
		
		
		// also on IWD, extend the level blocks for the BG2 version to 30th level
		
		ACTION_IF is_iwd BEGIN
			spl.edit["%WIZARD_MORDENKAINENS_SWORD%"]
			[
				m.ab.clone{s_level=entry_index+21|match="s_level=20" number:i=10}
				m.ab_fx.alter{duration=p_level*6|match="p_level>20 && s_duration>0"}
			]
		
		END

	END


END
