
//////////////////////////////////////////////////////////////////////////////
////	Boneguards
//////////////////////////////////////////////////////////////////////////////
IF TRIGGER
	RequireBlock(HasL9)
	RequireBlock(IsNecromancer)
	RequireBlock(Refinements)
	TargetBlock(PCsPreferringWeak)
	TargetBlock(Celestials)
	TriggerBlock(Enemy)
THEN DO
       Combine()
       Action(SpellAreaRES,"tg#bone"|150|50)
END


//////////////////////////////////////////////////////////////////////////////
////	If you have a Planetar, summon it (NB: we only substitute Planetars if the
////	Improved Planetar component is installed)
//////////////////////////////////////////////////////////////////////////////

IF TRIGGER
	TargetBlock(PCsPreferringWeak)
	TargetBlock(Celestials)
	TriggerBlock(Enemy)
	RequireBlock(HasL9)
	IgnoreBlock(IsEvokerStreamline)
	!See([ENEMY.0.DARKPLANATAR]) // only one at a time
THEN DO
	Combine()
	Action(SpellAreaRESReplace,"dw#plane",WIZARD_SUMMON_PLANATAR_EVIL|150|50)
END

