DEFINE_ACTION_FUNCTION antimagic_penetrates_ii BEGIN

	OUTER_SPRINT desc_add @3700
 
	spl.edit[%WIZARD_PIERCE_SHIELD% %WIZARD_SPELL_STRIKE% %WIZARD_RUBY_RAY_OF_REVERSAL% %WIZARD_WARDING_WHIP% %WIZARD_PIERCE_MAGIC% %WIZARD_SPELL_THRUST% %WIZARD_SECRET_WORD%|edit_strrefs_in_place:i=1]
	[
		m_description:="%m_description%%WNL%%desc_add%"
		m_can_target_invisible=1
		LPF log_this INT_VAR repeat=0 STR_VAR file=scs_modified_spells.2da input="%sfo_filename%" END
	]

END
