DEFINE_ACTION_FUNCTION cure_cause_alignment BEGIN

       LAF check_ini STR_VAR ini=keep_cure_wounds_alignment_restrictions RET value END
       ACTION_IF !value BEGIN
           MAKE_PATCH
                CURE_CRITICAL_WOUNDS=>41000
                MASS_CURE=>41001
                HEAL=>41002
                HARM=>41003
   END
   ACTION_PHP_EACH patch_data AS spell=>strref BEGIN
      OUTER_SPRINT spellname EVAL "%CLERIC_%spell%%"
      OUTER_SPRINT scrollname EVAL "%CLERIC_%spell%_SCROLL%"
      OUTER_SPRINT oldstring (AT strref)
      COPY_EXISTING "%spellname%.spl" override
         LPF patch_text_entry INT_VAR loc=0x50 STR_VAR function=substitute_string arguments="~%oldstring%~=>null" END
         LPF SPL_unusable_good_priest STR_VAR arguments=0 END
         LPF SPL_unusable_evil_priest STR_VAR arguments=0 END
         LPF SPL_unusable_GEneutral_priest STR_VAR arguments=0 END
      BUT_ONLY
      ACTION_IF FILE_EXISTS_IN_GAME "%scrollname%.itm" BEGIN
        COPY_EXISTING "%scrollname%.itm" override
         LPF patch_text_entry INT_VAR loc=0x54 STR_VAR function=substitute_string arguments="~%oldstring%~=>null" END
         LPF SPL_unusable_good_priest STR_VAR arguments=0 END
         LPF ITM_unusable_evil_priest STR_VAR arguments=0 END
         LPF ITM_unusable_GEneutral_priest STR_VAR arguments=0 END
        BUT_ONLY
      END
   END
 END
       LAF include STR_VAR file=divine_spells_postproduction.tpa locbase="iwdspells/lib" END
       WITH_TRA "%scs_tra_loc%/english/dw_iwdspells_divine.tra"  "%scs_tra_loc%/%LANGUAGE%/dw_iwdspells_divine.tra" BEGIN
          LAF remove_cause_wounds_alignment_restrictions END
       END



END