DEFINE_ACTION_FUNCTION otiluke_save_for_half BEGIN

	spl.edit[%WIZARD_OTILUKES_FREEZING_SPHERE%|edit_strrefs_in_place:i=1]
	[
		m_description:=@40015
		PATCH_IF enhanced_edition BEGIN
			m.ab_fx.alter{s_save_for_half=1|match="s_opcode=12"}
		END ELSE BEGIN
			m.ab_fx.alter{s_save_vs_spell=0 s_dicenumber=s_dicenumber / 2 |match="s_opcode=12"}
			m.ab_fx.clone{s_save_vs_spell=1|match="s_opcode=12"}
		END
		
	
	]


END

