DEFINE_ACTION_FUNCTION ~power_word_blind~ BEGIN
  
  ACTION_CLEAR_ARRAY patch_data
  ACTION_DEFINE_ASSOCIATIVE_ARRAY patch_data BEGIN
     say_description => 216
     patch_ability_inline => ~projectile=>1~ //no projectile
  END
  LAF edit_spell STR_VAR spell=WIZARD_POWER_WORD_BLIND edits=patch_data END
  LAF edit_item STR_VAR item="%WIZARD_POWER_WORD_BLIND_SCROLL%" editstring=~say_description=>216~ END


END
