DEFINE_ACTION_FUNCTION rebalance_force_missiles BEGIN

    MAKE_PATCH
       say_description=>40200
       delete_ability=>"ability_min_level>16"
       patch_effect_inline=>"match=>~ability_min_level=16 and opcode=333~ parameter2=>15"
    END
    LAF edit_spell STR_VAR spell=MORDENKAINENS_FORCE_MISSILES edits=patch_data END
    
    LAF edit_item STR_VAR item="%WIZARD_MORDENKAINENS_FORCE_MISSILES_SCROLL%" editstring="say_description=>40200" END

END