DEFINE_ACTION_FUNCTION use_bg_holy_smite_unholy_blight BEGIN


	spl.edit["%CLERIC_HOLY_SMITE%" "%CLERIC_UNHOLY_BLIGHT%"|edit_strrefs_in_place:i=1]
	[
		old1:=@14
		new1:=@15
		old2:=@16
		new2:=@17
		m_description=m_description.patch{REPLACE_TEXTUALLY "%old1%" "%new1%";;REPLACE_TEXTUALLY "%old2%" "%new2%"}
		m.ab.delete{s_level>1}
		m.ab.clone{s_level=entry_index+2|number:i=29}
		m.ab_fx.alter{s_dicenumber=p_level;;s_dicesize=4|match="s_opcode=12"}
	]

END