IF
	!GlobalTimerNotExpired("castspell","LOCALS")
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_MIRROR_IMAGE)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",6)
		Spell(Myself,WIZARD_MIRROR_IMAGE)
END

IF
	!GlobalTimerNotExpired("castspell","LOCALS")
	See(NearestEnemyOf(Myself))
	HaveSpell(WIZARD_HASTE)
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",6)
		Spell(Myself,WIZARD_HASTE)
END