IF
	AttackedBy([GOODCUTOFF],DEFAULT)
	Global("TurnHostile","AR6106",0)
THEN
	RESPONSE #100
		SetGlobal("TurnHostile","AR6106",1)
END

IF
	Global("KillDrow","AR6106",1)
	Global("KillSelf","LOCALS",0)
THEN
	RESPONSE #100
		CreateVisualEffectObject("spdeath3",Myself)
		Kill(Myself)
		SetGlobal("KillSelf","LOCALS",1)
END

IF
	Global("TurnHostile","AR6106",1)
	Global("Enemy","LOCALS",0)
THEN
	RESPONSE #100
		Enemy()
		SetGlobal("Enemy","LOCALS",1)
END