IF
	AttackedBy([GOODCUTOFF],DEFAULT)
THEN
	RESPONSE #100
		SetGlobal("YUANTI_INFERNO","GLOBAL",1)
		Enemy()
		Continue()
END

IF
       Allegiance(Myself,ENEMY)
       !Global("YUANTI_INFERNO","GLOBAL",1)
THEN
    RESPONSE #100
		SetGlobal("YUANTI_INFERNO","GLOBAL",1)
		Continue()
END


IF
	!Global("inafight","LOCALS",1)
	!Detect(NearestEnemyOf(Myself))
        ActionListEmpty()
	!NearSavedLocation(Myself,"#savedloc",0)
THEN
	RESPONSE #100
		MoveToSavedLocationn("#savedloc","LOCALS")
END
