IF
	!Global("DMWWJaellatReinforce","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("DMWWJaellatReinforce","GLOBAL",1)
		CreateCreature("dw#drja1",[1292.684],0)
		CreateCreature("dw#drja3",[1124.826],0)
		CreateCreature("dw#drja3",[1638.839],0)
		CreateCreature("dw#drja3",[1009.1007],0)
		CreateCreature("dw#drja3",[750.1086],0)
		CreateCreature("dw#drja2",[560.873],0)
		CreateCreature("dw#drja3",[1393.1108],0)
END

