DEFINE_ACTION_FUNCTION iwdspells_run STR_VAR version="" BEGIN

	INCLUDE "%MOD_FOLDER%/iwdspells/iwdspells_extern.tpa"
	OUTER_SPRINT type "%version%"
	OUTER_SPRINT component_loc "iwdspells"
	LAF iwdspells_extern 
		STR_VAR type
				custom_includes="iwdspells/custom/cd_scroll_placement.tpa iwdspells/custom/cd_arcane_spell_use.tpa" 
				sfo_library_path="sfo2e" 			// actually these are the default
	END

END