DEFINE_PATCH_FUNCTION process_menu_element
	STR_VAR name=""
	RET_ARRAY element_data 
BEGIN
	// process any sub-elements
	PATCH_FOR_EACH element IN list button text label column BEGIN
		index=0
		element_count=0
		WHILE INDEX_BUFFER ("%element%[^0-9a-z]*{" index)>=0 BEGIN
			element_count +=1
			index=INDEX_BUFFER ("%element%[^0-9a-z]*{" index)
			LPF find_parenthesis_range INT_VAR index RET start end END
			READ_ASCII start+1 data (end - start)
			DELETE_BYTES start+1 (end - start)
			INNER_PATCH_SAVE data "%data%" BEGIN
				LPF process_menu_element STR_VAR name="%name%.%element%%element_count%" RET_ARRAY element_data_here=element_data END
				LPF array_join STR_VAR array1=element_data array2=element_data_here RET_ARRAY element_data=array END
			END
			SPRINT replace_array("PLACEHOLDER_%element%_%element_count%") "%data%"
			index=end			
		END
	END


	
	
	

END
