

DEFINE_ACTION_FUNCTION test BEGIN

ACTION_IF GAME_IS iwdee BEGIN

  //  OUTER_SPRINT component_loc genai
  //  LAF run STR_VAR file=genai_iwd END
    LAF include STR_VAR file=research_iwd_scripts.tph END
    LAF kit_research END

END ELSE BEGIN

     LOAD_TRA "%scsroot%/lang/english/dw_iwdspells_divine.tra"
     LAF remove_cause_wounds_alignment_restrictions END
  //   LAF make_scroll_of_spell INT_VAR price=5000 STR_VAR resref="%CLERIC_UNHOLY_BLIGHT%" scrollname=testscrl END

END


END


