

DEFINE_ACTION_FUNCTION test BEGIN

ACTION_IF GAME_IS iwdee BEGIN

  //  OUTER_SPRINT component_loc genai
  //  LAF run STR_VAR file=genai_iwd END
    LAF include STR_VAR file=research_iwd_scripts.tph END
    LAF specifics_research END

END ELSE BEGIN
      OUTER_SPRINT component_loc tactical_bg1
      LAF get_area_script STR_VAR area="%SWBaldursGate_MerchantLeague_L3%" RET script END
      LAF edit_script STR_VAR script editstring="patch=>delete_action_if(dopzorl)" END
      LAF extend STR_VAR script top=merchant_league_roof ssl=yes location=ssl END



END


END


