INCLUDE ~%scsroot%/lib/ai_wrap.tph~

DEFINE_ACTION_FUNCTION test BEGIN

ACTION_IF GAME_IS iwdee BEGIN

  //  OUTER_SPRINT component_loc genai
  //  LAF run STR_VAR file=genai_iwd END
    LAF include STR_VAR file=research_iwd_scripts.tph END
    LAF specifics_research END

END ELSE BEGIN

       LAF edit_creature STR_VAR creature="pumberl pumber2" tv=1 editstring="insert_script_low=>priest3" END

       LAF clone_creature STR_VAR creature="pumber2=>dw#pumb3 pumber2=>dw#pumb4" END
       MAKE_PATCH
          patch_actor_inline=>"match=>~actor_x_coord_start=1029 and actor_resource=%tutu_var%pumber2~ actor_resource=>dw#pumb3"
          patch_actor_inline'=>"match=>~actor_x_coord_start=936 and actor_resource=%tutu_var%pumber2~ actor_resource=>dw#pumb4"
       END
       LAF edit_area STR_VAR area="%BaldursGateDocks_WaterQueensHouse%" edits=patch_data END

       LAF edit_creature STR_VAR creature="pumberl pumber2 dw#pumb3 dw#pumb4" editstring="enforce_priest=>null" END

END

END

DEFINE_PATCH_FUNCTION replace_with_777
INT_VAR strref=0
RET strref_new
BEGIN
   SET strref_new=777
END


