
////    Note that this block does not have a
////    GlobalTimerNotExpired("castspell","LOCALS") prefix, so that
////    the priest will attack until the power is triggered or lost


IF TRIGGER
        SSLBoolean(CLERIC_HARM) 
        HasItem("harm",Myself)
	Target(WorstAC())
	TargetBlock(PCsInOrder)
	TargetBlock(EnemiesInOrderShort)
	!HPPercentLT(scstarget,10)
	Range(scstarget,10)
	TriggerBlock(SpellTurn|SINecromancy|MirrorImage|MR|ResistMagicDamage)
	!CheckStat(scstarget,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
THEN DO
	Action(Attack)
END

IF TRIGGER
        SSLBoolean(CLERIC_CAUSE_CRITICAL_WOUNDS) 
        HasItem("critical",Myself))
	Target(WorstAC())
	TargetBlock(PCsInOrder)
	TargetBlock(EnemiesInOrderShort)
	Range(scstarget,10)
	TriggerBlock(SpellTurn|SINecromancy|MirrorImage|MR|ResistMagicDamage)
	!CheckStat(scstarget,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
THEN DO
	Action(Attack)
END

IF TRIGGER
        SSLBoolean(CLERIC_CAUSE_SERIOUS_WOUNDS)
        HasItem("serious",Myself)
	Target(WorstAC())
	TargetBlock(PCsInOrder)
	TargetBlock(EnemiesInOrderShort)
	Range(scstarget,10)
	TriggerBlock(SpellTurn|SINecromancy|MirrorImage|MR|ResistMagicDamage)
	!CheckStat(scstarget,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
THEN DO
	Action(Attack)
END

IF TRIGGER
        SSLBoolean(CLERIC_CAUSE_MODERATE_WOUNDS)
        HasItem("moderate",Myself)
	Target(WorstAC())
	TargetBlock(PCsInOrder)
	TargetBlock(EnemiesInOrderShort)
	Range(scstarget,10)
	TriggerBlock(SpellTurn|SINecromancy|MirrorImage|MR|ResistMagicDamage)
	!CheckStat(scstarget,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
THEN DO
	Action(Attack)
END

IF TRIGGER
        SSLBoolean(CLERIC_CAUSE_LIGHT_WOUNDS)
        HasItem("light",Myself)
	Target(WorstAC())
	TargetBlock(PCsInOrder)
	TargetBlock(EnemiesInOrderShort)
	Range(scstarget,10)
	TriggerBlock(SpellTurn|SINecromancy|MirrorImage|MR|ResistMagicDamage)
	!CheckStat(scstarget,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
THEN DO
	Action(Attack)
END


IF TRIGGER
        SSLBoolean(CLERIC_SLAY_LIVING)
        HasItem("slaylive",Myself)
	Target(WorstAC())
	TargetBlock(PCsInOrder)
	TargetBlock(EnemiesInOrderShort)
	Range(scstarget,10)
	TriggerBlock(SpellTurn|SINecromancy|MR|MirrorImage|Slay)
	!CheckStat(scstarget,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
THEN DO
	Action(Attack)
END
