
IF
	!Global("DavaeornBehavior","%CloakwoodMines_L4%",4)
	!Global("DavaeornBehavior","%CloakwoodMines_L4%",0)
	!See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		MoveToPoint([1332.401])
END

IF
	Dead("davaeorn")
THEN
	RESPONSE #100
		Kill(Myself)
END

IF
	See("davaeorn")
	See(LastAttackerOf("davaeorn"))
	!Allegiance(LastAttackerOf("davaeorn"),ENEMY)
THEN
	RESPONSE #100
		AttackReevaluate(LastAttackerOf("davaeorn"),30)
END
