
VARIABLE(HasL1=True)
VARIABLE(HasL2=True)
VARIABLE(HasL3=True)
VARIABLE(HasL4=True)
VARIABLE(HasL5=True)
VARIABLE(slowspell=)
//////////////////////////////////////////////////////////////////////////////////
///
///   Define actions
///
////////////////////////////////////////////////////////////////////////////////////////

BEGIN LOOP(scsspellsubstitute1||!StateCheck(scstarget,STATE_NOT_TARGETABLE))
BEGIN LOOP(scsspellsubstitute2||!StateCheck(scstarget,STATE_INVISIBLE))
	INCLUDE FILE(%scsroot%/mage/ssl/mage_definitions.ssl)
END LOOP
END LOOP

/////////////////////////////////////////////////////////
/////      Initial material
////////////////////////////////////////////////////////


IF
	Detect([PC])
	Range(LastSeenBy(Myself),15)
	NumTimesTalkedTo(0)
	AreaCheck("AR0900")
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		StartDialogueNoSet(LastSeenBy(Myself))
END


INCLUDE FILE (%scsroot%\mage\ssl\bg2\generalblocks\rest.ssl)
INCLUDE FILE (%scsroot%\mage\ssl\bg2\generalblocks\findhidden.ssl)
INCLUDE FILE (%scsroot%\mage\ssl\bg2\generalblocks\gohostile.ssl)

///////////////////////////////////////////////////////////////////////////////////////
///	Set up triggers
///////////////////////////////////////////////////////////////////////////////////////

IF
	Global("setuptriggers","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("setuptriggers","LOCALS",1)
		SetGlobal("MinorSequencer","LOCALS",21)
		Continue()
END

/////////////////////////////////////////////////////////////////////////////
////	Preps
//////////////////////////////////////////////////////////////////////////////

IF
	Global("instantprep","LOCALS",0)
	RequireBlock(HasL4)
	IgnoreBlock(HasNoPrep)
	!HasItem("dw#nopre",Myself)
THEN
	RESPONSE #100
		ApplySpellRES("%WIZARD_STONE_SKIN_PREBUFF%",Myself)
		SetGlobal("nocaststoneskin","LOCALS",0)
		Continue()
END

INCLUDE FILE(%scsroot%/mage/ssl/bg2/prepblocks/instantprep.ssl)
INCLUDE FILE(%scsroot%/priest/ssl/bg2/prepblocks/instantprep.ssl)


///////////////////////////////////////////////////////////////////
///  Set the redefend timer, to avoid recasting everything
////////////////////////////////////////////////////////////////////

IF
	Global("instantprep","LOCALS",0)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobal("instantprep","LOCALS",1)
		SetGlobalTimer("redefend","LOCALS",3)
		Continue()
END

////////////////////////////////////////////////////////////////////////
// Initialise for combat
////////////////////////////////////////////////////////////////////////

IF
	Global("inafight","LOCALS",0)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobal("inafight","LOCALS",1)
		Continue()
END


//////////////////////////////////////////////////////////////////////
///CPU saver
//////////////////////////////////////////////////////////////////////

IF
	!Detect(NearestEnemyOf(Myself))
	!HPPercentLT(Myself,100)
	!Global("inafight","LOCALS",1)
THEN
	RESPONSE #100
		NoAction()
END



///////////////////////////////////////////////////////////////////////////
//	Melee
///////////////////////////////////////////////////////////////////////////

INCLUDE FILE(%scsroot%/mage/ssl/bg2/generalblocks/melfsetup.ssl)
INCLUDE FILE(%scsroot%/mage/ssl/bg2/meleeblocks/fmmelee.ssl)

//////////////////////////////////////////////////////////////////////////
// Renew and retreat
//////////////////////////////////////////////////////////////////////////

DEFAULT TRIGGER(!GlobalTimerNotExpired("castspell","LOCALS"))

INCLUDE FILE(%scsroot%/caster_shared/clericmage/ssl/renew.ssl)

//////////////////////////////////////////////////////////////////////////
// Look for PCs
//////////////////////////////////////////////////////////////////////////

DEFAULT TRIGGER()

INCLUDE FILE(%scsroot%/mage/ssl/bg2/generalblocks/mill.ssl)
INCLUDE FILE(%scsroot%/mage/ssl/bg2/generalblocks/chase.ssl)

////////////////////////////////////////////////////////////////////////////
// Core magic block
///////////////////////////////////////////////////////////////////////////


DEFAULT TRIGGER(!GlobalTimerNotExpired("castspell","LOCALS"))



INCLUDE FILE(%scsroot%\priest\ssl\bg2\combatblocks\greater_command.ssl)
INCLUDE FILE(%scsroot%\mage\ssl\bg2\combatblocks\mid_level_area.ssl)
INCLUDE FILE(%scsroot%\priest\ssl\bg2\combatblocks\my_defences.ssl)
INCLUDE FILE(%scsroot%\priest\ssl\bg2\combatblocks\holy_smite.ssl)
INCLUDE FILE(%scsroot%\mage\ssl\bg2\combatblocks\low_level_disabling.ssl)
INCLUDE FILE(%scsroot%\priest\ssl\bg2\combatblocks\lowpowered_attacks.ssl)
INCLUDE FILE(%scsroot%\priest\ssl\bg2\combatblocks\command_and_attack.ssl)
INCLUDE FILE(%scsroot%\mage\ssl\bg2\combatblocks\arrows.ssl)



DEFAULT TRIGGER()



//////////////////////////////////////////////////////
////	If we get this far, we can't find anything to do, so
////	set the timer (this means we attack in the gap) 
//////////////////////////////////////////////////////

IF
!GlobalTimerNotExpired("castspell","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("castspell","LOCALS",6)
END
	

////////////////////////////////////////////////////////
///	Closedown: avoid interaction with other scripts
////////////////////////////////////////////////////////////

IF
	!See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		NoAction()
END
