//Incremental update for TobEx beta 0025

//Externalise Bard Song Effects
LAF tobex_copy STR_VAR file = "bardsong.spl" END

//Expanded Triggers
LAF tobex_copy STR_VAR file = "asgnspec.ids" END

APPEND "trigger.ids" "0x411F CheckStatBAND(O:Object*,I:Value*,I:StatNum*Stats)" UNLESS "0x411F CheckStatBAND(O:Object*,I:Value*,I:StatNum*Stats)"

//Externalise Difficulty Damage Modifier
LAF tobex_copy STR_VAR file = "diffmod.2da" END
