///////////////////////////////////////////////////////////////////////////////
///////   This is used via INCLUDE; don't use MAKE_PATCH or PUSH
///////////////////////////////////////////////////////////////////////////////

LAF include STR_VAR file=ai_shared.tph locbase=lib END
LAUNCH_ACTION_MACRO read_in_instant_prebuff_spells

LAF data_proficiencies RET_ARRAY weapprof profs profsmax END
OUTER_SET proficiencies_read_in=1

