
BEGIN LOOP(scsplayernum||1;2;3;4;5;6)

IF
  RequireBlock(EnhancedEdition)
  Allegiance(Myself,ENEMY)
  Range(Playerscsplayernum,30)
  !GlobalTimerNotExpired("thief_detection","LOCALS")
  CheckStatGT(Playerscsplayernum,65,DETECTILLUSIONS)
  ModalStateObject(Playerscsplayernum,DETECTTRAPS)
THEN  
      RESPONSE #100
               SetGlobalTimer("thief_detection","LOCALS",5)
               Continue()
END

END LOOP

