IF
	Detect([PC])
	Global("ThiefLine","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("ThiefLine","LOCALS",1)
		DisplayStringHead(Myself,52329) // Hah! Fool thief!
END

IF
	See([PC])
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		Shout(99)
		Enemy()
END

IF
	See([PC])
	!Allegiance(Myself,NEUTRAL)
	!Global("ThiefLine2","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("ThiefLine2","LOCALS",1)
		DisplayStringHead(Myself,52330) // More of the ilk! You shall die!
END


