
///////////////////////////////////////////////////////////////
///	Insect Plague etc
///////////////////////////////////////////////////////////////

IF TRIGGER
        IgnoreBlock(IsCleric)
	RequireBlock(HasL3)
	IgnoreBlock(SpellsAreBG1)
	TargetBlock(PCSpellcasters)
	TargetBlock(PCsInOrderShort)
	TriggerBlock(MR100Touch|SIConjuration|Enemy|Helpless)
	!CheckStatGT(scstarget,0,CLERIC_INSECT_PLAGUE)
	Global("shapeshift","LOCALS",0)
THEN DO
	Action(Spell,CLERIC_SUMMON_INSECTS|200|100)
END
