///////////////////////////////////////////////////////////////////////
/// Long-duration spells
///////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////
//	The point of SCSVAR is that everyone has this script twice -
//	once for if they appear far from their opponents, once for
//	if they appear in sight of them.
////////////////////////////////////////////////////////////////////////




//////////////////////////////////////////////////////////////
/// Ironskin - level 9+
//////////////////////////////////////////////////////////////

IF
	Global("longprep","LOCALS",0)
	RequireBlock(HasL5)
	RequireBlock(IsDruid)
	scsvar
THEN
	RESPONSE #100
		ApplySpellRES("dw#siron",Myself)
		Continue()
END

//////////////////////////////////////////////////////////////
/// Death Ward and Chaotic Commands - autocast
//////////////////////////////////////////////////////////////


IF
   Global("longprep","LOCALS",0)
   HaveSpell(CLERIC_DEATH_WARD)
   RequireBlock(HasL4)
   IgnoreBlock(SpellsAreBG1)
   scsvar
THEN 
     RESPONSE #100
              ApplySpellRES("dw#dthwd",Myself)
              RemoveSpell(CLERIC_DEATH_WARD)
              Continue()
END

IF
   Global("longprep","LOCALS",0)
   HaveSpell(CLERIC_CHAOTIC_COMMANDS)
   RequireBlock(HasL5)
   IgnoreBlock(SpellsAreBG1)
   scsvar
THEN 
     RESPONSE #100
              ApplySpellRES("dw#comcd",Myself)
              RemoveSpell(CLERIC_CHAOTIC_COMMANDS)
              Continue()
END