////////////////////////////////////////////////////////////////////////////
////MS 1
///////////////////////////////////////////////////////////////////////////

IF TRIGGER
	RequireBlock(HasL3)
	IgnoreBlock(IsInvoker)
	TargetBlock(PCsInReverseOrder)
	TargetBlock(EnemiesInOrderShort)
	TriggerBlock(Enemy)
	!CheckStatGT(Player1,6,Level)
	!HasItem("dw#area",Myself)
THEN DO
	Action(SpellArea,WIZARD_MONSTER_SUMMONING_1|70|30)
END

