////////////////////////////////////////////////////////////////////////////
////	The four-point saving throw penalty on the Wand of Paralysation means
////	that frankly you should use it as early and as often as possible
//////////////////////////////////////////////////////////////////////////////

IF TRIGGER
	TargetBlock(PCsPreferringStrong)
	TriggerBlock(Disabled|Paralyse|Enemy|MR)
THEN DO
	Action(Wand,"%tutu_var%wand04"|700|300)
END
