INCLUDE FILE(%scsroot%/mage/ssl/mage_definitions.ssl)

IF
	Allegiance(Myself,ENEMY)
	!Global("DMWWC3TentHostile","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("DMWWC3TentHostile","GLOBAL",1)
END

IF 
	!Allegiance(Myself,ENEMY)
	Global("DMWWC3TentHostile","GLOBAL",1)
THEN
	RESPONSE #100
		Enemy()
END

BEGIN LOOP(scsvar||1;2;3;4;5;6)

IF TRIGGER
                Global("DMWWC3TentHostile","GLOBAL",1)
THEN DO
                Action(FindIfOffscreen,Playerscsvar)
END

END LOOP
