IF
 Help([PC])
THEN
 RESPONSE #100 FaceObject(LastHelp(Myself)) Continue()
END
IF
 OR(2) Help([0.0.HUMAN]) Help([0.0.DWARF])
THEN
 RESPONSE #100 FaceObject(LastHelp(Myself)) Continue()
END
IF
 ActionListEmpty() NearSavedLocation(Myself,"#savedloc",0)
THEN
 RESPONSE #100 MoveToSavedLocation("#savedloc","LOCALS")
END
IF
 ActionListEmpty() !NearSavedLocation(Myself,"#savedloc",0)
THEN
 RESPONSE #100 RandomWalk() Wait(5)
END
