IF
 AttackedBy([GOODCUTOFF],DEFAULT)
THEN
 RESPONSE #100 SetGlobal("AREA_VARBit1","MYAREA",1) MoveToObject(LastAttackerOf(Myself))
END
IF
 Help([PC])
THEN
 RESPONSE #100 SetGlobal("AREA_VARBit1","MYAREA",1) MoveToObject(LastHelp(Myself))
END
IF
 Global("AREA_VARBit1","MYAREA",1) ActionListEmpty() !TargetUnreachable([PC])
THEN
 RESPONSE #100 MoveToObject([PC])
END
IF
 ActionListEmpty() !NearSavedLocation(Myself,"#savedloc",0)
THEN
 RESPONSE #100 MoveToSavedLocation("#savedloc","LOCALS")
END
