IF
 AttackedBy([GOODCUTOFF],DEFAULT)
THEN
 RESPONSE #100 SetGlobal("AREA_VARBit3","MYAREA",1) Enemy() Continue()
END
IF
 !Allegiance(Myself,ENEMY) See([PC]) !Allegiance(Myself,ENEMY) !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
 RESPONSE #100 StartCutSceneMode() ClearAllActions() MultiPlayerSync() EndCutSceneMode() StartDialogNoSet(PartySlot1)
END
IF
 ActionListEmpty() !NearSavedLocation(Myself,"#savedloc",0)
THEN
 RESPONSE #100 MoveToSavedLocation("#savedloc","LOCALS")
END
