IF TRIGGER
        RequireBlock(Demivrgvs)
	ConditionalTargetBlock(PCsPreferringWeak;HPPercentLT(scstarget,40))
	TargetBlock(PCsPreferringWeak)
	TriggerBlock(MR|ResistCold|Enemy|ArrowSafe|SpellTurn|MinorGlobe|Helpless|SIEvocation|MirrorImage)
THEN DO
	Action(Spell,CLERIC_ICELANCE|150|50)
END


IF TRIGGER
   RequireBlock(IsIWDDivine)
   TriggerBlock(Enemy|MR100|SpellTurn|MinorGlobe|DirectDamageSafe)
   TargetBlock(PCsPreferringWeak)
THEN DO
     Action(Spell,CLERIC_ALICORN_LANCE|100|50)
END
