
///////////////////////////////////////////////////////////////
///	Insect Plague etc
///////////////////////////////////////////////////////////////

IF TRIGGER
	TargetBlock(PCSpellcasters)
	TargetBlock(PCsInOrderShort)
	TriggerBlock(MR100NotSR|SIConjuration|Enemy|Helpless)
	!CheckStatGT(scstarget,0,CLERIC_INSECT_PLAGUE)
	Global("shapeshift","LOCALS",0)
THEN DO
	Action(Spell,CLERIC_SUMMON_INSECTS|200|100)
	Action(SpellRESBoolean,CLERIC_LOLTH_SUMMON_SPIDERS|200|100)
END
