//////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////
////	Vampire fear
//////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////

BEGIN LOOP(scsfearcheck||GlobalTimerNotExpired("seeimmune","LOCALS");TriggerBlock(Panic)&!GlobalTimerNotExpired("seeimmune","LOCALS")&CheckStatGT(scstarget,-2,SAVEVSSPELL))

/////////////////////////////////////////////////////////////////////////
//	Top priority: clerics and people with undead-slaying weapons
/////////////////////////////////////////////////////////////////////////

IF TRIGGER
        Global("causesfear","LOCALS",1)
	scsfearcheck
	!GlobalTimerNotExpired("fear","LOCALS")
	TargetBlock(PlayersInOrder)
	TriggerBlock(MR|SIEnchantment|SpellTurn|Enemy|Helpless)
	OR(4)
		Class(scstarget,CLERIC_ALL)
		HasItem("blun12",scstarget)
		HasItem("blun25",scstarget)
		HasItem("ax1h10",scstarget)
THEN DO
	SetGlobalTimer("fear","LOCALS",12)
	Action(ForceSpell,VAMPIRE_FEAR|100|100)
END

/////////////////////////////////////////////////////////////////////////
//	Then try for anyone you can get
/////////////////////////////////////////////////////////////////////////

IF TRIGGER
        Global("causesfear","LOCALS",1)
	scsfearcheck
	!GlobalTimerNotExpired("fear","LOCALS")
	ConditionalTargetBlock(PlayersInOrder;!CheckStatGT(scstarget,50,RESISTMAGIC))
	TargetBlock(PlayersInOrder)
	TriggerBlock(MR|SIEnchantment|SpellTurn|Enemy|Helpless)
THEN DO
	SetGlobalTimer("fear","LOCALS",12)
	Action(ForceSpell,VAMPIRE_FEAR|100|100)
END

END LOOP
