DEFINE_ACTION_FUNCTION extra_healing BEGIN

      LAF add_items_to_store STR_VAR store=tem2304 tv=yes location=~FIRST~ items=~potn52(3)~ END
      LAF add_items_to_store STR_VAR store=tem3402 tv=yes location=~FIRST~ items=~potn52(4)~ END
      LAF add_items_to_store STR_VAR store=tem0132 tv=yes location=~FIRST~ items=~potn52(4)~ END
      LAF add_items_to_store STR_VAR store=tem0131 tv=yes location=~FIRST~ items=~potn52(6)~ END
END
