DEFINE_ACTION_FUNCTION fine_arrows BEGIN

    MAKE_PATCH
      magical=>0
      lore=>0
      enchantment=>0
      patch_ability_inline=>~projectile=>"object_index from [5 15 35 20]"~
      say_both_names=>"object_index from [20305 20307 20309 20311]"
      say_both_descriptions=>"object_index from [20306 20308 20310 20312]"
      delete_opcodes=>233
    END
    LAF edit_item STR_VAR item="arow02 bolt02 dart02 bull02" edits=patch_data END

END