DEFINE_ACTION_FUNCTION use_iwd_blade_barrier_saving_throw BEGIN

	// descriptions
	
	spl.edit["%CLERIC_BLADE_BARRIER%"|edit_strrefs_in_place:i=1][m_description:=@7]
	spl.edit["%CLERIC_GLOBE_OF_BLADES%"|edit_strrefs_in_place:i=1 allow_missing:i=1][m_description:=@8]
	
	// payload

	spl.edit[sppr603d sppr698d sppr725d spyancd|allow_missing:i=1]
	[
		m.ab_fx.alter{s_save_for_half=1|match="s_opcode=12"}
	]

END