DEFINE_ACTION_FUNCTION ~ease_of_use_ai~ BEGIN

    LAF ssl_to_bcs STR_VAR script=0dw#gen END
    COPY_EXISTING ~0dw#gen.bcs~ ~scripts\0dw#gen.bs~

    LAF install STR_VAR file=dw#alac.spl END // this is adapted from (though non-identical to) WW's "wesalac" spell

    OUTER_SET namestrref=RESOLVE_STR_REF(@605)
    OUTER_SET descstrref=RESOLVE_STR_REF(@606)

    COPY_EXISTING ~SCRPDESC.2DA~ ~OVERRIDE~
	INSERT_2DA_ROW 0 3 ~0dw#gen %namestrref% %descstrref%~
    BUT_ONLY

END