DEFINE_ACTION_FUNCTION protect_sharteel BEGIN

      LAF edit_creature STR_VAR creature=~sharte sharte4 sharte6~ tv=1 editstring=~add_items=>"monhp1(RRING)"~ END

<<<<<<<< .../stratagems-inline/sharadd.baf
IF
	InParty(Myself)
	HasItem("monhp1",Myself)
THEN
	RESPONSE #100
		DestroyItem("monhp1")
END
>>>>>>>>

     LAF extend STR_VAR file= ~%tutu_scripts%harteel~ top=sharadd inline=yes END

END              
