IF TRIGGER
        RequireBlock(EasyOptionAvailable)
        TriggerBlock(EasyMinus)
	See([PC])
	NumTimesTalkedTo(0)
THEN DO
		Dialogue([PC])
END

IF TRIGGER
        RequireBlock(EasyOptionAvailable)
        TriggerBlock(CorePlus)
	NumTimesTalkedTo(0)
	See([PC])
THEN DO
		StartDialogueNoSet([PC])
END


IF
	IgnoreBlock(EasyOptionAvailable)
        NumTimesTalkedTo(0)
	See([PC])
THEN
	RESPONSE #100
		StartDialogueNoSet([PC])
END