
//////////////////////////////////////////////////////////////////////////////////
//      Handle fear
//////////////////////////////////////////////////////////////////////////////////

IF
  RequireBlock(EnhancedEdition)
  StateCheck(Myself,STATE_PANIC)
  Range(NearestEnemyOf(Myself),10)
THEN
    RESPONSE #100
             RunAwayFromNoLeaveArea(NearestEnemyOf(Myself),15)
END

IF
  StateCheck(Myself,STATE_PANIC)
THEN
    RESPONSE #100
             RandomWalkContinuous()
END