/////////////////////////////////////////////////////////////////////
/// Set up definitions
////////////////////////////////////////////////////////////////////

BEGIN LOOP(scsspellsubstitute1|| )
BEGIN LOOP(scsspellsubstitute2|| )
	INCLUDE FILE (%scsroot%\psionic\ssl\psionic_defs.ssl)
END LOOP
END LOOP

INCLUDE FILE(%scsroot%\psionic\ssl\illithid\flayertop.ssl)

DEFAULT TRIGGER(!GlobalTimerNotExpired("castspell","LOCALS"))

/////////////////////////////////////////////////////////////////////////
///	Psionic Blast
/////////////////////////////////////////////////////////////////////////
IF TRIGGER
	TargetBlock(PCsInOrder)
	TargetBlock(EnemiesInOrderShort)
	!GlobalTimerNotExpired("firstblast","LOCALS")
	TriggerBlock(Enemy|Helpless)
THEN DO
	Combine()
	SetGlobalTimer("firstblast","LOCALS",1000)
	Action(Psionic,BRAIN_PSIONIC_BLAST,psionicblast,12|200|50)
END
IF TRIGGER
	TargetBlock(PCsInOrder)
	TargetBlock(EnemiesInOrderShort)
	TriggerBlock(Stun|Enemy|Helpless|PsiBlast)
THEN DO
	Combine()
	Action(Psionic,BRAIN_PSIONIC_BLAST,psionicblast,12|200|50)
END

///////////////////////////////////////////////////////////////////////////////
////	Melee
///////////////////////////////////////////////////////////////////////////////

DEFAULT TRIGGER()

INCLUDE FILE(%scsroot%\psionic\ssl\illithid\mfcombat.ssl)
