// Eat brains

IF TRIGGER
	TargetBlock(PCsInOrder)
	Range(scstarget,5)
	TriggerBlock(Enemy|Plus2Safe)
	StateCheck(scstarget,STATE_IMMOBILE)
THEN DO
	Action(Attack)
END

// More conventional combat block

BEGIN LOOP(MyWeaponStrength||2)
BEGIN LOOP(MyWeaponDamageType||Null)
INCLUDE FILE(%scsroot%\genai\ssl\dw#wtacor.ssl)
INCLUDE FILE(%scsroot%\genai\ssl\move.ssl)
END LOOP
END LOOP

// no need for a Chase block, the existing Jump block covers it fine
