DEFINE_ACTION_FUNCTION basilisk BEGIN

   ACTION_IF GAME_IS ~tutu tutu_totsc~ BEGIN
     OUTER_SPRINT ~greater_basilisk_script~ ~_8_gbasi~
   END ELSE BEGIN
     OUTER_SPRINT ~greater_basilisk_script~ ~gbasilsk~
   END
   LAF ssl_to_bcs STR_VAR script=~lbasilsk~ location=~ai/ssl~ rename_to=EVALUATE_BUFFER ~%tutu_scriptl%basilsk~ END
   LAF ssl_to_bcs STR_VAR script=gbasilsk location=~ai/ssl~ rename_to=EVALUATE_BUFFER ~%greater_basilisk_script%~ END

END