DEFINE_ACTION_FUNCTION sirine_dryad BEGIN

   LAF include STR_VAR file=caster_shared.tph locbase=caster_shared END
   LAUNCH_ACTION_MACRO read_in_instant_prebuff_spells

   LAF define_difficulty STR_VAR type=genai RET difficulty_variable END

   LAF ssl_to_bcs STR_VAR script="sirspell=>%tutu_scripts%irspell" location=ssl END
   LAF ssl_to_bcs STR_VAR script="hama=>%tutu_var%hama" location=ssl END


END
