
DEFINE_ACTION_FUNCTION beholder_hive BEGIN

        // strip any QP remnant
        LAF get_area_script STR_VAR area=ar2101 RET script END
        LAF DELETE_SCRIPT_BLOCK STR_VAR script match=d0toughen END

        // add my version

        LAF define_difficulty STR_VAR type=beholder_hive RET difficulty_variable END
        LAF extend_area_script STR_VAR area=ar2101 top=ar2101add location=ssl ssl=yes END

END
