INCLUDE ~%scsroot%/lib/ai_wrap.tph~

DEFINE_ACTION_FUNCTION c7throne BEGIN

   LAF edit_creature STR_VAR creature=wudei tv=1 editstring=~alignment=>NEUTRAL_EVIL~ END

   MAKE_PATCH
      shaldr=>13
      rahvin=>11
      haseo=>11
      wudei=>12
   END
   ACTION_PHP_EACH patch_data AS creaturename=>level BEGIN
      LAF edit_creature STR_VAR creature= ~%tutu_var%%creaturename%~ editstring= ~level=>%level% enforce_charclass=>is_bg1~ END
   END

END

