INCLUDE ~%scsroot%/lib/ai_wrap.tph~

DEFINE_ACTION_FUNCTION redwizard BEGIN
    LAF run STR_VAR file=creature_swaps END

   MAKE_PATCH
      denak=>9
      brenda=>7
      lasala=>6
      diana=>8
   END
   ACTION_PHP_EACH patch_data AS creaturename=>level BEGIN
      LAF diff_based_clone STR_VAR creature=~%tutu_var%%creaturename%~ hardname=~dw%creaturename%~ editstring=~level=>%level% enforce_charclass=>is_bg1~ END
   END
END
