VARIABLE(ImmuneToNormal=True)
VARIABLE(HasL1=True)
VARIABLE(HasL2=True)
VARIABLE(HasL3=True)
VARIABLE(HasL4=True)
VARIABLE(HasL5=True)
VARIABLE(HasL6=True)
VARIABLE(HasL7=True)
VARIABLE(HasL8=True)
VARIABLE(HasL9=True)
VARIABLE(IsOption3=True)
VARIABLE(HasNoPrep=True)
VARIABLE(HasNoContingency=True)
VARIABLE(IsHighLevel=True)
VARIABLE(IsKensai=True)


//////////////////////////////////////////////////////////////////////////////////
///
///   Define actions
///
////////////////////////////////////////////////////////////////////////////////////////

BEGIN LOOP(scsspellsubstitute1|| )
BEGIN LOOP(scsspellsubstitute2|| )
BEGIN LOOP(AttackReevaluate(scstarget,30)||AttackOneRound(scstarget))
	INCLUDE FILE(%scsroot%/mage/ssl/mage_definitions.ssl)
END LOOP
END LOOP
END LOOP


IF
	HPLT(Myself,20)
	Global("DeathScriptAbaz","AR6200",0)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("DeathScriptAbaz","AR6200",1)
		ClearActions(Myself)
		CreateVisualEffectObject("ICRMPARI",Myself)
		CreateVisualEffectObject("SPROTECT",Myself)
		ActionOverride("finmel01",ClearActions(Myself))
		ActionOverride("finmel01",DestroyItem("finabaz")) // Abazigal
		ReallyForceSpellDeadRES("melspl10","finmel01") // Feedback
		Kill(Myself)
END

IF
	Global("IMPRISON","LOCALS",1)
	Global("AbazigalImprisoned","AR6200",0)
THEN
	RESPONSE #100
		ClearActions(Myself)
		SetInterrupt(FALSE)
		SetGlobal("IMPRISON","LOCALS",0)
		SetGlobal("AbazigalImprisoned","AR6200",1)
		DisplayStringHead(Myself,46151) // help!
		SetInterrupt(TRUE)
END

////////////////////////////////////////////////////////////////////////
/////////	no preps
////////////////////////////////////////////////////////////////////////

IF
   !GlobalGT("longprep","LOCALS",0)
THEN
    RESPONSE #100
             SetGlobal("longprep","LOCALS",1)
             Continue()
END

////////////////////////////////////////////////////////////////////////
/////////	short-term preps
////////////////////////////////////////////////////////////////////////

IF
   !Global("instantprep","LOCALS",1)
THEN 
   RESPONSE #100
       SetGlobal("instantprep","LOCALS",1)
       Continue()
END



////////////////////////////////////////////////////////////////////////
/////////	triggers
////////////////////////////////////////////////////////////////////////

IF
	Global("setuptriggers","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("SpellTrigger","LOCALS",2)
		SetGlobal("SpellSequencer","LOCALS",2)
		SetGlobal("MinorSequencer","LOCALS",1)
		SetGlobal("setuptriggers","LOCALS",1)
		SetGlobal("inafight","LOCALS",1)
		Continue()
END

////////////////////////////////////////////////////////////////////////
/////////	Contingency
////////////////////////////////////////////////////////////////////////

IF
	!Global("ChainContingencyFired","LOCALS",1)
THEN
	RESPONSE #100
			SetGlobal("ChainContingencyFired","LOCALS",1)
			DisplayStringHead(Myself,26328)
			ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
			ReallyForceSpell(Myself,WIZARD_IMPROVED_HASTE)
			ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)
			SetGlobalTimer("redefend","LOCALS",3)
			SetGlobal("inafight","LOCALS",1)
			Continue()
END



////////////////////////////////////////////////////////////////////////////
///	Contingencies renew defences
////////////////////////////////////////////////////////////////////////////

INCLUDE FILE(%scsroot%/mage/ssl/bg2/generalblocks/contingency.ssl)



///////////////////////////////////////////////////////////////////////////
////	Flee Cloudkill spell
///////////////////////////////////////////////////////////////////////////

INCLUDE FILE(%scsroot%/mage/ssl/bg2/generalblocks/fleecloud_fm.ssl)


///////////////////////////////////////////////////////////////////////////
//	Melee
///////////////////////////////////////////////////////////////////////////

DEFAULT TRIGGER(GlobalTimerNotExpired("castspell","LOCALS"))

INCLUDE FILE(%scsroot%/mage/ssl/bg2/meleeblocks/FMmelee.ssl)

//////////////////////////////////////////////////////////////////////////
// Renew and retreat
//////////////////////////////////////////////////////////////////////////

DEFAULT TRIGGER(!GlobalTimerNotExpired("castspell","LOCALS"))

INCLUDE FILE(%scsroot%/mage/ssl/bg2/generalblocks/renew.ssl)

//////////////////////////////////////////////////////////////////////////
// Look for PCs
//////////////////////////////////////////////////////////////////////////

DEFAULT TRIGGER()

INCLUDE FILE(%scsroot%/mage/ssl/bg2/generalblocks/mill.ssl)

DEFAULT TRIGGER(!GlobalTimerNotExpired("castspell","LOCALS"))


INCLUDE FILE(%scsroot%/mage/ssl/bg2/generalblocks/chase.ssl)

////////////////////////////////////////////////////////////////////////////
// Core magic block
///////////////////////////////////////////////////////////////////////////

BEGIN LOOP(slowspell|| )
INCLUDE FILE(%scsroot%/mage/ssl/bg2/magetypes/fighter_mage.ssl)
END LOOP

INCLUDE FILE(%scsroot%/mage/ssl/bg2/generalblocks/closedown.ssl)
