IF
	HPPercentLT(Myself,15)
	HPPercentGT(Myself,0)
	Range(NearestEnemyOf(Myself),10)
	HPPercentGT(NearestEnemyOf(Myself),20)
	Global("GateAway","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("GateAway","LOCALS",1)
		SpellNoDec(Myself,DRYAD_TELEPORT)
END

IF
	Allegiance(Myself,ALLY)
	!Detect([ENEMY])
	CombatCounter(0)
	Global("GateAway","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("GateAway","LOCALS",1)
		SpellNoDec(Myself,DRYAD_TELEPORT)
END


//////////////////////////////////////////////////////////////////////////////////////////
///	Ascension control block
//////////////////////////////////////////////////////////////////////////////////////////


INCLUDE FILE(%scsroot%/ascension/ssl/asc_control.ssl)

//////////////////////////////////////////////////////////////////////////////////////////
///	Core Alu-Fiend script
//////////////////////////////////////////////////////////////////////////////////////////


INCLUDE FILE(%scsroot%/fiend/ssl/demalu01.ssl)
