
//////////////////////////////////////////////////////////////////////////////////////////
///	Ascension control block
//////////////////////////////////////////////////////////////////////////////////////////


INCLUDE FILE(%scsroot%/ascension/ssl/asc_control.ssl)

//////////////////////////////////////////////////////////////////////////////////////////
///	Gates
//////////////////////////////////////////////////////////////////////////////////////////

IF TRIGGER
	Allegiance(Myself,ENEMY)
	!GlobalTimerNotExpired("castspell","LOCALS")
	NumCreatureLT([ENEMY.0.DEMONIC],3)
	Global("gated","LOCALS",0)
	!Range(NearestEnemyOf(Myself),10)

	TriggerBlock(CorePlus)
THEN DO
                Action(Literal|100|100)
                SetGlobalTimer("castspell","LOCALS",6)
		ForceSpellRES("GATE5",Myself) // Gate
END

IF
	!GlobalTimerNotExpired("castspell","LOCALS")
	HPPercentLT(Myself,15)
	!HPPercentLT(Myself,0)
	Range(NearestEnemyOf(Myself),10)
	HPPercentGT(NearestEnemyOf(Myself),20)
	Global("GateAway","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("GateAway","LOCALS",1)
		SetGlobalTimer("Running","LOCALS",2)
		CreateVisualEffectObject("SPSUMGTE",Myself)
		SmallWait(8)
		CreateVisualEffectObject("SPFLESHS",Myself)
		DisplayString(Myself,14260) // Gate
		DestroySelf()
END


//////////////////////////////////////////////////////////////////////////////////////
///	Core combat script
//////////////////////////////////////////////////////////////////////////////////////

INCLUDE FILE(%scsroot%/fiend/ssl/dembal01.ssl)