VARIABLE(YagaFinale=True)

IF TRIGGER
	Global("IMPRISON","LOCALS",1)
	Global("YagaImprisoned","AR6200",0)
	TriggerBlock(EasyPlus)
THEN DO
                Action(Literal)
		ClearActions(Myself)
		SetInterrupt(FALSE)
		SetGlobal("IMPRISON","LOCALS",0)
		SetGlobal("YagaImprisoned","AR6200",1)
		DisplayStringHead(Myself,46151) // help!
		SetInterrupt(TRUE)
END


INCLUDE FILE(%scsroot%/ascension/ssl/yagaft.ssl)