IF
	!Global("instantprep","LOCALS",1)
THEN
	RESPONSE #100
		ReallyForceSpell(Myself,WIZARD_SPELL_TRAP)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_THE_ELEMENTS)
		ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_DIVINATION)
		ReallyForceSpell(Myself,WIZARD_GLOBE_OF_INVULNERABILITY)
		ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY)
		ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)
		ReallyForceSpell(Myself,WIZARD_IMPROVED_HASTE)
		SetGlobal("instantprep","LOCALS",1)
		Continue()
END

