/////////////////////////////////////////////////////////////////////
////      Invoke a Cloak of Fear
/////////////////////////////////////////////////////////////////////

IF TRIGGER
          RequireBlock(HasL4)
          TargetBlock(PCsInOrderShort)
          Range(scstarget,6)
          TriggerBlock(Enemy|Disabled|Panic)
THEN DO
       Combine()
       Action(Spell,CLERIC_CLOAK_OF_FEAR|100|100)
END

////////////////////////////////////////////////////////////////////
///    Generate a weapon if needed
///////////////////////////////////////////////////////////////////

IF TRIGGER
          IgnoreBlock(IsDruid)
          RequireBlock(HasL2)
          IgnoreBlock(Demivrgvs)
          TargetBlock(PCsInOrderShort)
          Range(scstarget,6)
          !Class(Myself,FIGHTER_ALL)
THEN DO
       Action(Spell,CLERIC_SPIRITUAL_HAMMER)
END

IF TRIGGER
          IgnoreBlock(IsDruid)
          RequireBlock(HasL2)
          RequireBlock(Demivrgvs)
          TargetBlock(PCsInOrderShort)
          Range(scstarget,20)
          !Class(Myself,FIGHTER_ALL)
THEN DO
       Action(Spell,CLERIC_SPIRITUAL_HAMMER)
END

IF TRIGGER
          RequireBlock(IsDruid)
          TargetBlock(PCsInOrderShort)
          Range(scstarget,6)
          !Class(Myself,FIGHTER_ALL)
THEN DO
       Action(Spell,CLERIC_SHILLELAGH)
END

////////////////////////////////////////////////////////////////////
////////	This is the point to use a "Command-and-attack"
////////	routine on anyone in strike range
///////////////////////////////////////////////////////////////////

IF TRIGGER
	IgnoreBlock(IsDruid)
	TargetBlock(PCsInOrderShort)
	Range(scstarget,6)
	TriggerBlock(Disabled|Hold|MinorGlobe|MR|Enemy)
THEN DO
	Action(Spell,CLERIC_COMMAND)
	SetGlobalTimer("killhelpless","LOCALS",6)
END

