

/////////////////////////////////////////////////////////////////////////////
/////  Finger of Death
///////////////////////////////////////////////////////////////////////////

IF TRIGGER
	ConditionalTargetBlock(PCsPreferringWeak;!CheckStatGT(scstarget,50,RESISTMAGIC))
	TargetBlock(EnemiesInOrderShort)
	TriggerBlock(MR100|SpellTurnNew|Enemy)
THEN DO
	Action(Spell,CLERIC_FINGER_OF_DEATH|100|300)
END

/////////////////////////////////////////////////////////////////////////////
/////  Searing Orb
///////////////////////////////////////////////////////////////////////////

IF TRIGGER
        IgnoreBlock(Demivrgvs)
	ConditionalTargetBlock(PCsPreferringWeak;!CheckStatGT(scstarget,50,RESISTMAGIC))
	TargetBlock(EnemiesInOrderShort)
	TriggerBlock(MR100|SpellTurn|ResistFire|SIEvocation|Enemy)
	TriggerBlock(DirectDamageSafe)
THEN DO
        Combine()
	Action(Spell,CLERIC_SOL_SEARING_ORB|100|100)
END

/////////////////////////////////////////////////////////////////////////////
/////  Talos Lightning Bolt
///////////////////////////////////////////////////////////////////////////


IF TRIGGER
        RequireBlock(IsTalosar)
	TargetBlock(EnemiesInOrder)
	TriggerBlock(Enemy|MR|ResistElectric|SIEvocation|MirrorImage)
	TriggerBlock(DirectDamageSafe)
THEN DO
	Combine()
	Action(SpellArea,TALOS_LIGHTNING_BOLT|100|50)
END

