

/////////////////////////////////////////////////////////////////////////////
/////  Finger of Death
///////////////////////////////////////////////////////////////////////////

IF TRIGGER
	ConditionalTargetBlock(PCsPreferringStrong;!CheckStatGT(scstarget,50,RESISTMAGIC))
	TargetBlock(EnemiesInOrderShort)
	TriggerBlock(MR100|SpellTurn|Slay|SINecromancy|Enemy)
	!HasItemEquiped("clck26",scstarget)
THEN DO
	Action(Spell,CLERIC_FINGER_OF_DEATH|100|300)
END

/////////////////////////////////////////////////////////////////////////////
/////  Searing Orb
///////////////////////////////////////////////////////////////////////////

IF TRIGGER
	ConditionalTargetBlock(PCsPreferringWeak;!CheckStatGT(scstarget,50,RESISTMAGIC))
	TargetBlock(EnemiesInOrderShort)
	TriggerBlock(MR100|SpellTurn|ResistFire|SIEvocation|Enemy)
	!HasItemEquiped("clck26",scstarget)
THEN DO
        Combine()
	Action(Spell,CLERIC_SOL_SEARING_ORB|100|100)
END

/////////////////////////////////////////////////////////////////////////////
/////  Talos Chain Lightning
///////////////////////////////////////////////////////////////////////////


IF TRIGGER
	TargetBlock(EnemiesInOrder)
	TriggerBlock(Enemy|MR|ResistElectric|SIEvocation|MirrorImage)
	!HasItemEquiped("clck26",scstarget)
THEN DO
	Combine()
	Action(SpellRES,"CDTLCNL"|100|50)
END

