

/////////////////////////////////////////////////////////////////////////////
/////  Implosion
///////////////////////////////////////////////////////////////////////////

IF TRIGGER
	RequireBlock(HasL7)
	ConditionalTargetBlock(PCsPreferringWeak;CheckStatGT(scstarget,40,RESISTMAGIC))
	TargetBlock(PCsPreferringWeak)
	TargetBlock(Celestials)
	TriggerBlock(SpellTurn|SIEvocation|Enemy|Helpless)
	!HasItemEquiped("clck26",scstarget)
THEN DO
	Action(Spell,CLERIC_IMPLOSION|150|50)
END

