
////////////////////////////////////////////////////////////////////
////	Touch attacks
///////////////////////////////////////////////////////////////////

IF TRIGGER
    IgnoreBlock(IsDruid)
	RequireBlock(HasL6)
	TargetBlock(PCsInOrderShort)
	Range(scstarget,10)
	TriggerBlock(Enemy)
	Global("shapeshift","LOCALS",0)
	!HasItem("dw#harmn",Myself)
	!HasItem("harm",Myself)
	!HasItem("critical",Myself)
	!HasItem("serious",Myself)
	!HasItem("slaylive",Myself)
THEN DO
	Action(SpellMyselfRESReplace,"dw#harmn",CLERIC_HARM)
END

IF TRIGGER
	RequireBlock(HasL5)
	IgnoreBlock(SpellsAreBG1)
	IgnoreBlock(IsDruid)
	TargetBlock(EnemiesInOrderShort)
	Range(scstarget,10)
	TriggerBlock(Enemy|Slay|SpellTurnNew)
	!HasItem("dw#harmn",Myself)
	!HasItem("harm",Myself)
	!HasItem("critical",Myself)
	!HasItem("serious",Myself)
	!HasItem("slaylive",Myself)
THEN DO
	Combine()
	Action(SpellMyself,CLERIC_SLAY_LIVING|100|50)
END

IF TRIGGER
    IgnoreBlock(IsDruid)
	RequireBlock(HasL4)
	RequireBlock(Demivrgvs)
	TargetBlock(PCsInOrderShort)
	Range(scstarget,10)
	TriggerBlock(Enemy|ResistMagicDamage|SpellTurnNew)
	!HasItem("dw#harmn",Myself)
	!HasItem("harm",Myself)
	!HasItem("critical",Myself)
	!HasItem("serious",Myself)
	!HasItem("slaylive",Myself)
THEN DO
        Combine()
	Action(SpellMyself,CLERIC_CAUSE_SERIOUS_WOUNDS)
	Action(SpellRESMyself,"sppr321")
END


