
////////////////////////////////////////////////////////////////////
////	Touch attacks
///////////////////////////////////////////////////////////////////

IF TRIGGER
	RequireBlock(HasL6)
	TargetBlock(PCsInOrderShort)
	Range(scstarget,10)
	!CheckStat(scstarget,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	TriggerBlock(SpellTurn|MR|Enemy|SINecromancy|ResistMagicDamage)
	Global("shapeshift","LOCALS",0)
	!HasItem("dw#harmn",Myself)
	!HasItem("harm",Myself)
	!HasItem("critical",Myself)
	!HasItem("serious",Myself)
	!HasItem("slaylive",Myself)
THEN DO
	Action(SpellMyselfRESReplace,"dw#harmn",CLERIC_HARM)
END

IF TRIGGER
	RequireBlock(HasL5)
	IgnoreBlock(SpellsAreBG1)
	IgnoreBlock(IsDruid)
	TargetBlock(EnemiesInOrderShort)
	Range(scstarget,10)
	!CheckStat(scstarget,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	TriggerBlock(SpellTurn|MR|Enemy|Slay|SINecromancy)
	!HasItem("clck26",scstarget)
	!HasItem("dw#harmn",Myself)
	!HasItem("harm",Myself)
	!HasItem("critical",Myself)
	!HasItem("serious",Myself)
	!HasItem("slaylive",Myself)
THEN DO
	Combine()
	Action(SpellMyself,CLERIC_SLAY_LIVING|100|50)
END

IF TRIGGER
	RequireBlock(HasL4)
	RequireBlock(Demivrgvs)
	TargetBlock(PCsInOrderShort)
	Range(scstarget,10)
	!CheckStat(scstarget,4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	TriggerBlock(SpellTurn|MR|Enemy|SINecromancy|ResistMagicDamage)
	!HasItem("dw#harmn",Myself)
	!HasItem("harm",Myself)
	!HasItem("critical",Myself)
	!HasItem("serious",Myself)
	!HasItem("slaylive",Myself)
THEN DO
        Combine()
	Action(SpellMyself,CLERIC_CAUSE_SERIOUS_WOUNDS)
	Action(SpellRESMyself,"sppr321")
END


