/////////////////////////////////////////////////////////
/////      Initial material
////////////////////////////////////////////////////////

INCLUDE FILE (%scsroot%/mage/ssl/bg2\generalblocks\rest.ssl)
INCLUDE FILE (%scsroot%/mage/ssl/bg2\generalblocks\findhidden.ssl)
INCLUDE FILE (%scsroot%/mage/ssl/bg2\generalblocks\gohostile.ssl)


///////////////////////////////////////////////////////
// Long-term defences
//////////////////////////////////////////////////////

INCLUDE FILE (%scsroot%/mage/ssl/bg2\prepblocks\longprep_bard.ssl)

///////////////////////////////////////////////////////////////////
// "Instant-up" defences
///////////////////////////////////////////////////////////////////

INCLUDE FILE(%scsroot%/mage/ssl/bg2\prepblocks\instantprep.ssl)

///////////////////////////////////////////////////////////////////
///  Set the redefend timer, to avoid recasting everything
////////////////////////////////////////////////////////////////////

IF
	IgnoreBlock(IsOptionThree)
	Global("instantprep","LOCALS",0)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobal("instantprep","LOCALS",1)
		SetGlobalTimer("redefend","LOCALS",5)
		Continue()
END


IF
	RequireBlock(IsOptionThree)
	Global("instantprep","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("instantprep","LOCALS",1)
		SetGlobalTimer("redefend","LOCALS",0)
		Continue()
END

		


////////////////////////////////////////////////////////////////////////
// Set up spell triggers
////////////////////////////////////////////////////////////////////////

INCLUDE FILE(%scsroot%/mage/ssl/bg2\prepblocks\bardtrig.ssl)

/////////////////////////////////////////////////////////////////////////
///	Enter fight mode if you detect trouble (mostly for undead)
/////////////////////////////////////////////////////////////////////////

IF
	Allegiance(Myself,ENEMY)
    OR(12)
      AttackedBy([GOODCUTOFF.0.0.0.0.SUMMONED],DEFAULT)
      AttackedBy([PC],DEFAULT)
      AttackedBy([FAMILIAR],DEFAULT)
      AttackedBy([ALLY],DEFAULT)
      AttackedBy([CONTROLLED],DEFAULT)
      AttackedBy([CHARMED],DEFAULT)
      SpellCastOnMe([GOODCUTOFF.0.0.0.0.SUMMONED],0)
      SpellCastOnMe([PC],0)
      SpellCastOnMe([FAMILIAR],0)
      SpellCastOnMe([ALLY],0)
      SpellCastOnMe([CONTROLLED],0)
      SpellCastOnMe([CHARMED],0) 
!Global("inafight","LOCALS",1)
  !See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    SetGlobal("inafight","LOCALS",1)
    Continue()
END	

////////////////////////////////////////////////////////////////////////
// Initialise for combat
////////////////////////////////////////////////////////////////////////

IF
	Global("inafight","LOCALS",0)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetGlobal("inafight","LOCALS",1)
		Continue()
END




//////////////////////////////////////////////////////////////////////
///CPU saver
//////////////////////////////////////////////////////////////////////

IF
	!Detect(NearestEnemyOf(Myself))
	!HPPercentLT(Myself,100)
	!Global("inafight","LOCALS",1)
THEN
	RESPONSE #100
		NoAction()
END


