


//////////////////////////////////////////////////////////////////
///////    Go hostile (code borrowed from Weimer tactics)
//////////////////////////////////////////////////////////////////

IF
    !Allegiance(Myself,ENEMY)
    OR(7)
      AttackedBy([GOODCUTOFF.0.0.0.0.SUMMONED],DEFAULT)
      AttackedBy([PC],DEFAULT)
      AttackedBy([FAMILIAR],DEFAULT)
      AttackedBy([ALLY],DEFAULT)
      AttackedBy([CONTROLLED],DEFAULT)
      AttackedBy([CHARMED],DEFAULT)
      SpellCastOnMe([GOODCUTOFF.0.0.0.0.SUMMONED],0)
THEN
  RESPONSE #100
      Enemy()
      Continue()
END


/////////////////////////////////////////////////////////////////
///	Block to prevent neutrals prebuffing
/////////////////////////////////////////////////////////////////

IF	
	!Allegiance(Myself,ENEMY)
	!Global("DMWWNeutralPrebuff","GLOBAL",1)
THEN
	RESPONSE #100
		NoAction()
END

